### ISSUE TITLE
Compilation issue for glossary

### ISSUE THREAD

**Issue by xeruf** [openpatch/hyperbook#219]
On our current main branch, don't quite know what could be causing this: https://github.com/software-challenge/docs
CC @FalconsSky
```sh
info  - Collecting page data  
[    ] info  - Generating static pages (0/96)
Error occurred prerendering page "/glossary". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property '0' of undefined
    at getStaticProps (/home/janek/data/1-projects/software-challenge/docs/hyperbook/.hyperbook/.next/server/pages/glossary.js:75:33)
    at renderToHTML (/home/janek/data/1-projects/software-challenge/docs/hyperbook/.hyperbook/node_modules/next/dist/server/render.js:368:26)
    at async /home/janek/data/1-projects/software-challenge/docs/hyperbook/.hyperbook/node_modules/next/dist/export/worker.js:259:36
    at async Span.traceAsyncFn (/home/janek/data/1-projects/software-challenge/docs/hyperbook/.hyperbook/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (96/96)
```

**Comment by mikebarkmin** [comment]
Maybe a glossary page does not have a name property.

```
---
name: My page
---
```

Possibly it should default to the file name or there could be a better error message.
