### ISSUE TITLE
Server Error - Error: Error serializing 'navigation .current. repo' returned from 'getStaticProps' in "/[[...page]]"

### ISSUE THREAD

**Issue by cejuo** [openpatch/hyperbook#576]
Hello, this error appears when running `npx hyperbook dev` after creating a new default book with `npx hyperbook new my-new-hyperbook`.
Does someone know how to fix it?

Capture:
![Screenshot 2023-01-08 at 10 32 17](https://user-images.githubusercontent.com/101661143/211189193-1f4c7861-edde-475f-8cd5-19acf2de4cb7.png)

Terminal output: 
```
> @platforms/web@0.13.1 next:dev
> next-hyperbook-watch

event - compiled client and server successfully in 1297 ms (3151 modules)
> Ready on http://localhost:3000
wait  - compiling /[[...page]] (client and server)...
event - compiled client and server successfully in 512 ms (3443 modules)
error - SerializableError: Error serializing `.navigation.current.repo` returned from `getStaticProps` in "/[[...page]]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at isSerializable (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:36:19)
    at /Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:43:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at /Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:43:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at /Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:43:66
    at Array.every (<anonymous>)
    at isSerializable (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at Object.isSerializableProps (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/lib/is-serializable-props.js:63:12)
    at Object.renderToHTML (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/server/render.js:440:93)
    at async doRender (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/server/base-server.js:720:34)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/j/Documents/test/.hyperbook/node_modules/next/dist/server/base-server.js:828:28)
    at async /Users/j/Documents/test/.hyperbook/node_modules/next/dist/server/response-cache/index.js:83:36 {
  page: '/[[...page]]'
}
```

**Comment by mikebarkmin** [comment]
Thank you for discovering this bug. For the moment, you can set the `repo` property in the hyperbook.json. 

The fix will be released in a couple of minutes, after the pipelines went through.

**Comment by mikebarkmin** [comment]
The fix got released. Be sure to upgrade to version `0.13.2`.
